version: 0.0
os: linux

files:
  - source: chalna-server-0.0.1-SNAPSHOT.zip
    destination: /home/ubuntu/app/chalna-server/
    overwrite: yes

permissions:
  - object: /home/ubuntu/app/chalna-server/
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 120
      runas: root
