name: Deploy to EC2

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up environment variables
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> $GITHUB_ENV
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> $GITHUB_ENV
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "FIREBASE_SERVICE_ACCOUNT_KEY=${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" >> $GITHUB_ENV
          echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew build -x test  # 필요에 따라 테스트를 포함하도록 변경

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: spring-boot-app
          path: build/libs/*.jar

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: spring-boot-app
          path: .

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          github_token: ${{secrets.TOKEN}}
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ubuntu
            rm -rf chalna-server-0.0.1-SNAPSHOT.jar
            mv ~/spring-boot-app-*.jar /home/ubuntu/chalna-server-0.0.1-SNAPSHOT.jar
            # 환경 변수 설정
            export DB_HOST=${{ secrets.DB_HOST }}
            export DB_PORT=${{ secrets.DB_PORT }}
            export DB_NAME=${{ secrets.DB_NAME }}
            export DB_USERNAME=${{ secrets.DB_USERNAME }}
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            export CLIENT_ID=${{ secrets.CLIENT_ID }}
            export CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
            export FIREBASE_SERVICE_ACCOUNT_KEY=${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
            export JWT_SECRET=${{ secrets.JWT_SECRET }}
            export REDIS_HOST=${{ secrets.REDIS_HOST }}
            export REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
            export REDIS_POST=${{ secrets.REDIS_PORT }}
            
            # JVM 옵션 설정
            export JAVA_OPTS="-Duser.timezone=Asia/Seoul"
            # 기존 실행 중인 애플리케이션 종료 (선택 사항)
            pkill -f 'java -jar /home/ubuntu/chalna-server-0.0.1-SNAPSHOT.jar'
            # 새로운 애플리케이션 시작
            nohup java -jar $JAVA_OPTS /home/ubuntu/chalna-server-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &
