name: Deploy to EC2

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: spring-boot-app
          path: build/libs/*.jar

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: spring-boot-app
          path: .

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          github_token: ${{secrets.TOKEN}}
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ubuntu
            rm -rf chalna-server-0.0.1-SNAPSHOT.jar
            mv ~/spring-boot-app-*.jar /home/ubuntu/chalna-server-0.0.1-SNAPSHOT.jar
            # 환경 변수 로드
            export $(cat .env | xargs)
            # JVM 옵션 설정
            export JAVA_OPTS="-Duser.timezone=Asia/Seoul"
            # 기존 실행 중인 애플리케이션 종료 (선택 사항)
            pkill -f 'java -jar /home/ubuntu/chalna-server-0.0.1-SNAPSHOT.jar'
            # 새로운 애플리케이션 시작
            nohup java -jar $JAVA_OPTS /home/ubuntu/chalna-server-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &
